name: hijri_gregorian_calendar
description: A Flutter package to convert and display Hijri and Gregorian calendars.
version: 0.1.0
homepage: https://github.com/amirsaleemahmad/hijri_gregorian_calendar
repository: https://github.com/amirsaleemahmad/hijri_gregorian_calendar
documentation: https://github.com/amirsaleemahmad/hijri_gregorian_calendar#readme


environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
